#cloud-config
power_state:
  mode: poweroff
runcmd:
  - [sh, -c, 'cat /etc/netplan/netplan.yaml > /var/tmp/netplan.yaml']
  - [sh, -c, 'ip -oneline link show > /var/tmp/ip_link']
  - [sh, -c, 'ip -oneline -4 addr show > /var/tmp/ip_addr']
  - [sh, -c, 'ip -oneline -6 addr show > /var/tmp/ip_addr_6']
  - [sh, -c, 'ip -oneline -4 route show > /var/tmp/ip_route']
  - [sh, -c, 'ip -oneline -6 route show > /var/tmp/ip_route_6']
  - [sh, -c, 'bridge link show > /var/tmp/bridge_link']
  - [sh, -c, 'systemd-resolve --status > /var/tmp/systemd_resolve']
  - [sh, -c, 'networkctl status > /var/tmp/networkctl_status']
  - [sh, -c, 'cat /run/NetworkManager/system-connections > /var/tmp/nm_sys_connections']
