# Bonding Mode 0: balance-rr
#
# This mode is based on Round-robin policy and it is the default mode. This
# mode offers fault tolerance and load balancing features. It transmits the
# packets in Round robin fashion that is from the first available slave
# through the last.
#
# https://help.ubuntu.com/community/UbuntuBonding#Descriptions_of_bonding_modes
#
network:
    renderer: networkd
    ethernets:
        net0:
            match:
                macaddress: 52:54:00:12:34:04
        net1:
            match:
                macaddress: 52:54:00:12:34:05
    bonds:
        bond0:
            dhcp4: yes
            interfaces:
                - net0
                - net1
            parameters:
                mode: balance-rr
