# Bonding Mode 3: broadcast
#
# This method is based on broadcast policy that is it transmitted everything
# on all slave interfaces. It provides fault tolerance.
#
# https://help.ubuntu.com/community/UbuntuBonding#Descriptions_of_bonding_modes
#
network:
    renderer: networkd
    ethernets:
        net0:
            match:
                macaddress: 52:54:00:12:34:04
        net1:
            match:
                macaddress: 52:54:00:12:34:05
    bonds:
        bond0:
            dhcp4: yes
            interfaces:
                - net0
                - net1
            parameters:
                mode: broadcast
