# Bonding Mode 1: active-backup
#
# This mode is based on Active-backup policy. Only one slave is active in this
# band, and another one will act only when the other fails. The MAC address of
# this bond is available only on the network adapter part to avoid confusing
# the switch. This mode also provides fault tolerance.
#
# https://help.ubuntu.com/community/UbuntuBonding#Descriptions_of_bonding_modes
#
network:
    renderer: networkd
    ethernets:
        net0:
            match:
                macaddress: 52:54:00:12:34:04
        net1:
            match:
                macaddress: 52:54:00:12:34:05
    bonds:
        bond0:
            dhcp4: yes
            interfaces:
                - net0
                - net1
            parameters:
                primary: net0
