# Routes on IPv4 and IPv6
#
# https://wiki.ubuntu.com/ModularEtcNetworkInterfacesSpec
# https://wiki.ubuntu.com/IPv6
#
network:
    version: 2
    renderer: networkd
    ethernets:
        net0:
            addresses:
                - 10.0.0.10/24
            match:
                macaddress: 52:54:00:12:34:04
            routes:
                - to: 10.1.0.1
                  via: 10.0.0.1
        net1:
            addresses:
                - 10.0.1.10/24
            match:
                macaddress: 52:54:00:12:34:05
            routes:
                - to: 10.1.1.1
                  via: 10.0.1.1
        net2:
            addresses:
                - 10.0.2.10/24
            match:
                macaddress: 52:54:00:12:34:06
            routes:
                - to: 10.1.2.1
                  via: 10.0.2.1
        net3:
            addresses:
                - 10.0.3.10/24
            match:
                macaddress: 52:54:00:12:34:07
            routes:
                - to: 10.1.3.1
                  via: 10.0.3.1
